dist: trusty
install: true
sudo: required
script:
  - mkdir ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - sudo apt install bc
  - sudo apt install pxz
  - sudo apt install wput
  - travis_wait 60 ./dependencies-skadoo.sh
